-- Müşteri listesini customers tablosuna ekle
-- Mevcut müşteriler varsa hata vermez (ON CONFLICT ile)

INSERT INTO public.customers (name) VALUES
  ('Acar Kuyumculuk'),
  ('Ahmet Demirci'),
  ('Akdere Kuyumculuk'),
  ('Aksoy Kuyumculuk'),
  ('Ali Taş Delen Kuyumculuk'),
  ('Altın Marka'),
  ('Altınbaşak Kuyumculuk'),
  ('Aslan Kuyumculuk'),
  ('Ay Kuyumculuk'),
  ('Bade Kuyumculuk'),
  ('Başak Kuyumculuk'),
  ('Berk Kuyumculuk'),
  ('Burçak Kuyumculuk'),
  ('Cansu Kuyumculuk'),
  ('Deniz Alyans'),
  ('Dünya Kuyumculuk'),
  ('Ece Kuyumculuk'),
  ('Elif (Akdere)'),
  ('Elmadağ Safir'),
  ('Emek Kuyumculuk'),
  ('Emir Kuyumculuk Toptan'),
  ('Emre Kuyumculuk'),
  ('Erçağ Kuyumculuk'),
  ('Erdoğan Alyans'),
  ('Erol Usta'),
  ('Ertekin Kuyumculuk'),
  ('Erva Kuyumculuk'),
  ('Esenboğa Kuyumculuk'),
  ('Esta Kuyumculuk'),
  ('Fidan Kuyumculuk'),
  ('Güneş Kuyumculuk'),
  ('Güneyler Kuyumculuk'),
  ('Hamit Gold'),
  ('Harika Kuyumculuk'),
  ('Has Kuyumculuk'),
  ('Hasan Fidan'),
  ('Hasan Usta'),
  ('Hazer Kuyumculuk'),
  ('Hazine Kuyumculuk'),
  ('Helena Kuyumculuk'),
  ('Hisar Köklü Kuyumculuk'),
  ('Hisar Kuyumculuk'),
  ('Işıltı Toptan'),
  ('İlim Kuyumculuk'),
  ('İlkar Kuyumculuk'),
  ('Kaya Kuyumculuk'),
  ('Merve Kuyumculuk'),
  ('Mizan Kuyumculuk'),
  ('Murat Tamirat'),
  ('Nakkaf Kuyumculuk'),
  ('Navan Kuyumculuk'),
  ('Nehir Kuyumculuk'),
  ('Nil Kuyumculuk'),
  ('Öz Anadolu Kuyumculuk'),
  ('Özkoçak Kuyumculuk'),
  ('Pan Kuyumculuk'),
  ('Pehlivan Kuyumculuk'),
  ('Saçak Kuyumculuk'),
  ('Samet Pursaklar'),
  ('Semih Kuyumculuk Toptan'),
  ('Sıla Kuyumculuk'),
  ('Şah Kuyumculuk'),
  ('Şakir Keçiören'),
  ('Şakir Komşu'),
  ('Şakir Kuyumculuk'),
  ('Şanlı Toptan'),
  ('Truva Kuyumculuk'),
  ('Tsrm Alyans'),
  ('Tuana (Ahmet Abi)'),
  ('Uğur Böceği Kuyumculuk'),
  ('Yaprak Kuyumculuk'),
  ('Yasemin Kuyumculuk'),
  ('Yasir Kuyumculuk'),
  ('Yıldız Kuyumculuk'),
  ('Yusuf Toptan'),
  ('Zerafet Kuyumculuk'),
  ('Zerda Kuyumculuk'),
  ('Zirve Kuyumculuk')
ON CONFLICT (name) DO NOTHING;

-- Toplam eklenen müşteri sayısını kontrol et
SELECT COUNT(*) as total_customers FROM public.customers;
